### PR TITLE
feat: use defined temp unit

### PR DESCRIPTION
**Pull request by is343**
This PR fixes the issue mentioned in #11. 

- It uses the defined unit of measurement from the temperature entity's attributes.
- It will fallback to `'°C'` if `unit_of_measurement` is missing.
- Ran the `build` script to generate the distribution file with `rollup`

image

### CODE REVIEW

**Comment by is343** [comment]
Actually, I removed that extra space I added. It was uneven because the humidity does not have an empty space between the number and the % symbol. 

~I didn't run the `build` script again to update the dist file.~ I figure you can do that whenever you're ready to increment the version number and release. Let me know if you'd like me to do that @sicknesz 

EDIT:
I did run `build` and pushed the updated dist file again

**Comment by is343** [comment]
@sicknesz any update on when this can get reviewed?

**Comment by yieldhog** [comment]
Would love to get this integrated.

**Comment by sicknesz** [comment]
Sorry for the HUGE delay in responding, im merging it right now

**Pull request merged**
